cart/urls.py
from django.urls import path

from . import views
app_name = 'cart'

urlpatterns = [
    path('', views.details, name='details'),
    path('add/<int:clothing_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:clothing_id>/', views.cart_remove, name='cart_remove')
]

fashionfury/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('myapp.urls', namespace='myapp')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('create/', views.create_order, name='create_order')
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
CLOTHING_QUANTITY_CHOICES = [(i, str(i)) for i in range(1,10)]
class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices = CLOTHING_QUANTITY_CHOICES,
        coerce=int, label='')

    new_quantity = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.http import HttpResponseRedirect
from django.urls import reverse
from myapp.models import Clothing
from .cart import Cart
from .forms import CartAddProductForm
from django.contrib.auth.decorators import login_required


# Create your views here.
@require_POST
@login_required(login_url='/login')
def cart_add(request, clothing_id):
    cart = Cart(request)
    clothing = get_object_or_404(Clothing, id=clothing_id)
    form = CartAddProductForm(request.POST)
    size = request.POST["sizes"]
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(clothing=clothing, quantity=cd['quantity'], size=size, new_quantity=cd['new_quantity'])
    return redirect('cart:details')

@login_required(login_url='/login')
def cart_remove(request, clothing_id):
    cart = Cart(request)
    clothing = get_object_or_404(Clothing, id=clothing_id)
    cart.remove(clothing)
    return redirect('cart:details')

@login_required(login_url='/login')
def details(request):
    # Get cart
    cart = Cart(request)
    return render(request, 'cart/cart_details.html', {'cart':cart})

cart/templates/cart/cart_details.html
{% extends "myapp/layout.html" %}

{% block body %}
<strong class="title">Cart</strong>
<section class="cart-products">
   {% for item in cart %}
      {% with clothing=item.clothing %}
      <div class="item">
         <img class="cart-img" src="{{ clothing.image.url }}" width=100%>
         <div class="cart-product">
            <a class="cart-title"> {{ clothing.name }}</a>
            <br>
            <span class="cart-quantity"> Quantity: {{ item.quantity }}</span>
            <br>
            <span class="cart-price">Price: ${{ item.price }}</span>
            <br>
            <span class="cart-size">Size: {{ item.size }}</span>
            <br>
            <form action="{% url 'cart:cart_remove' clothing.id %}" method="post">
               <input class="remove-btn" type="submit" value="Remove">
               {% csrf_token %}
            </form>
         </div>
      </div>
      <hr>
      {% endwith %}
   {% endfor %}

   <span class="cart-total">Total: ${{ cart.get_total_price }}</span>
   <div class="proceed-btn"><a class="checkout" href="{% url 'orders:create_order' %}">Proceed to Checkout</a></div>

</section>


{% endblock %}