cart/urls.py
from django.urls import path

from . import views
app_name = 'cart'

urlpatterns = [
    path('', views.details, name='details'),
    path('add/<int:clothing_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:clothing_id>/', views.cart_remove, name='cart_remove')
]

fashionfury/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('myapp.urls', namespace='myapp')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path

from . import views
app_name = 'myapp'

urlpatterns = [
    path('', views.homepage, name="homepage"),
    path('login', views.login_view, name="login"),
    path('logout', views.logout_view, name="logout"),
    path('register', views.register, name="register"),
    path('<slug:category_slug>/', views.get_clothes, name="get_clothes"),
    path('<slug:category_slug>/<str:gender>', views.gender_clothes, name="gender_clothes"),
    path('<int:clothing_id>/<slug:slug>/', views.clothing_description, name="clothing_description"),
    path('search', views.search, name="search")
]

myapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.

class User(AbstractUser):
    pass

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

class Clothing(models.Model):
    name = models.CharField(max_length=500)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    color = models.CharField(max_length=100)
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    slug = models.SlugField(max_length=200, db_index=True)
    available = models.BooleanField(default=True)
    gender = models.CharField(max_length=100)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'))

myapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect, Http404
from werkzeug.security import check_password_hash, generate_password_hash
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator



from .models import User, Category, Clothing
from cart.forms import CartAddProductForm

# Create your views here.
def homepage(request):
    return render(request, 'myapp/homepage.html')


def login_view(request):
    if request.method == "POST":
        # Attempt to sign user in
        email = request.POST["email"]
        object = User.objects.get(email=email)
        username = object.username
        #print(username)
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)


        # Check if authentication successful
        if user is not None:
            login(request, user)
            return redirect('myapp:homepage')
        else:
            return render(request, 'myapp/login.html', {
                "message": "Invalid username or password."
            })
    else:
        return render(request, 'myapp/login.html')

def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmed_pass = request.POST["confirm-password"]
        if password == confirmed_pass:
            user = User.objects.create_user(username, email, password)
            user.save()
            login(request, user)
            return redirect('myapp:homepage')
    else:
        return render(request, "myapp/register.html")


def get_clothes(request, category_slug=None):
    if category_slug:
        # Get category using category_slug
        category = Category.objects.get(slug=category_slug)
        if category:
            # Get clothes in the category
            clothes = Clothing.objects.filter(category=category)
    else:
        clothes = Clothing.objects.all()

    paginator = Paginator(clothes, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)


    return render(request, 'myapp/clothes.html', {
        "page_obj": page_obj
    })

def gender_clothes(request, category_slug=None, gender=None):
    if category_slug:
        try:
            category = Category.objects.get(slug=category_slug)
            if category:
                # Get clothes for a specific gender in a specific category
                clothes = Clothing.objects.filter(category=category, gender=gender)
        except Category.DoesNotExist:
            clothes = Clothing.objects.filter(gender=gender)

    paginator = Paginator(clothes, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'myapp/clothes.html', {
        "page_obj": page_obj
    })



def logout_view(request):
    logout(request)
    return redirect('myapp:homepage')


def clothing_description(request, clothing_id, slug):
    clothing = Clothing.objects.get(pk=clothing_id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'myapp/clothing_description.html', {
        "clothing": clothing,
        "cart_product_form": cart_product_form
    })

def search(request):
    if request.method == "POST":
        user_search = request.POST["search"]
        try:
            # Categorical searches
            category = Category.objects.get(slug=user_search)
        except Category.DoesNotExist:
            category = None
        clothes = Clothing.objects.all()
        matches = []
        for clothing in clothes:
            # Matches in clothing name or color
            if user_search in clothing.name.lower() or user_search in clothing.color.lower():
                matches.append(clothing)

        if len(matches) == 0:
            if category:
                searches = Clothing.objects.filter(category=category)
                return render(request, 'myapp/search.html',{
                    "clothes": searches
                })
            else:
                # No searches found
                return render(request, 'myapp/search.html',{
                    "clothes": None,
                    "message": "No searches found."
                })
        else:
            return render(request, 'myapp/search.html',{
                "clothes": matches
            })

myapp/templates/myapp/clothes.html
{% extends "myapp/layout.html" %}

{% block body %}
<section class="clothing-products">
   {% for clothing in page_obj %}
      <div class="product">
         <img class="clothing-img" src="{{ clothing.image.url }}" width=100%>
         <a id="clothing-title" href="{% url 'myapp:clothing_description' clothing_id=clothing.pk slug=clothing.slug %}" class="product-details"> {{ clothing.name }}</a>
         <br>
         <span class="product-details">${{ clothing.price }}</span>
      </div>
   {% endfor %}
</section>

   <div class="pagination">
      <span class="step-links">
         {% if page_obj.has_previous %}
            <a href="?page=1"> First</a>
            <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
         {% endif %}

         <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
         </span>

         {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Last </a>
         {% endif %}
      </span>
   </div>

{% endblock %}

myapp/templates/myapp/clothing_description.html
{% extends "myapp/layout.html" %}
{% load static %}


{% block body %}
   <div class="product_description_page">
      <img class="clothing-details-img" src="{{ clothing.image.url }}" width=60%>
      <div class="details">
         <a class="product-description-details"> {{ clothing.name }}</a>
         <br>
         <span class="product-description-details">${{ clothing.price }}</span>
      </div>

      <form class="add-to-bag" method="post" action="{% url 'cart:cart_add' clothing_id=clothing.pk %}">
         {% csrf_token %}
         <span class="cart-form">Quantity: {{ cart_product_form }}</span>
         <div class="sizes">
            <select name="sizes" id="sizes">
               <option value="xs">XS</option>
               <option value="small">Small</option>
               <option value="medium">Medium</option>
               <option value="large">Large</option>
            </select>
         </div>

         <div class="cart-btn">
            <input class="bag-btn" type="submit" value="Add To Cart">
         </div>
      </form>

      <span class="clothing-details">Details</span>
      <hr>

   </div>


{% endblock %}

myapp/templates/myapp/homepage.html
{% extends "myapp/layout.html" %}
{% load static %}


{% block body %}
<div class="image-container">
   <section class="image1">
      <img src="static/myapp/homepageimage1.jpg" width=100% class="image-gallery">
      <button class="shop-btn"> <a href="{% url 'myapp:gender_clothes' category_slug='None' gender='male' %}">Shop Men's</a></button>
   </section>
   <section class="image2">
      <img src="static/myapp/homepageimage2.jpg" width=100% class="image-gallery">
      <button class="shop-btn"><a href="{% url 'myapp:gender_clothes' category_slug='None' gender='female' %}">Shop Women's</a></button>

   </section>
</div>
{% endblock %}


{% block script %}
   <script src="{% static 'myapp/homepage.js' %}"></script>
{% endblock %}

myapp/templates/myapp/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
      <link href="{% static 'myapp/style.css' %}" rel="stylesheet">
      <link href='https://fonts.googleapis.com/css?family=Caveat Brush' rel='stylesheet'>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
      <title>{% block title %}Fashion FurI{% endblock %}</title>

      {% block script %}
      {% endblock %}

    </head>
    <body>
         <div class="container">
            <ul class="site-logo">
               <li><a href="/" id="logo" class="logo"> Fashion FurI</a></li>
            </ul>

            <nav class="first-nav">
               <ul class="first-nav-list">
                  {% if user.is_authenticated %}
                  <li class="first-nav-item">
                     <a class="first-nav-link">Hi, {{ request.user }}</a>
                     <ul class="dropdown-list">
                        <li class="dropdown-list-item">
                           <a href="{% url 'myapp:logout' %}" class="dropdown-list-link">Log Out</a>
                        </li>
                     </ul>
                  </li>
                  <li class="first-nav-item">
                     {% with total_items=cart|length %}
                        {% if total_items > 0 %}
                           <a href="{% url 'cart:details' %}" class="first-nav-link" id="cart"><i class="fas fa-shopping-cart"></i>Cart(<span> {{ total_items }} Items </span>)</a>
                        {% else %}
                           <a href="{% url 'cart:details' %}" class="first-nav-link" id="cart"><i class="fas fa-shopping-cart"></i>Cart(<span> 0 Items </span>)</a>
                           {% endif %}
                     {% endwith %}
                  </li>
                  {% else %}
                  <li class="first-nav-item">
                     <a href="{% url 'myapp:login' %}" class="first-nav-link"><i class="fas fa-sign-in-alt"></i>Sign Up / Log In</a>
                  </li>
                  <li class="first-nav-item">
                     <a href="#" class="first-nav-link"><i class="fas fa-shopping-cart"></i>Cart(<span> Items </span>)</a>
                  </li>
                  {% endif %}
               </ul>
            </nav>

            <div class="search">
               <form class="search-form" method="post" action="{% url 'myapp:search' %}">
                  {% csrf_token %}
                  <input type="text" class="search-input" name="search" placeholder="Search">
                  <button class="search-btn"><i class="fas fa-search"></i></button>
               </form>
            </div>

            <nav class="second-nav">
               <ul class="second-nav-list">
                  <li class="second-nav-item">
                     <a href="#" class="second-nav-link">All Items</a>
                     <ul class="dropdown-list">
                        <li class="dropdown-list-item">
                           <a href="{% url 'myapp:get_clothes' category_slug='tops' %}" class="dropdown-list-link">Tops</a>
                        </li>
                        <li class="dropdown-list-item">
                           <a href="{% url 'myapp:get_clothes' category_slug='bottoms' %}" class="dropdown-list-link">Bottoms</a>
                        </li>
                        <li class="dropdown-list-item">
                           <a href="{% url 'myapp:get_clothes' category_slug='sweaters' %}" class="dropdown-list-link">Sweaters</a>
                        </li>
                        <li class="dropdown-list-item">
                           <a href="{% url 'myapp:get_clothes' category_slug='jackets' %}" class="dropdown-list-link">Jackets</a>
                        </li>
                     </ul>
                  </li>
                  <li class="second-nav-item">
                     <a href="#" class="second-nav-link">Men</a>
                     <ul class="dropdown-list">
                        <li class="dropdown-list-item">
                           <a href="{% url 'myapp:gender_clothes' category_slug='tops' gender='male' %}" class="dropdown-list-link">Tops</a>
                        </li>
                        <li class="dropdown-list-item">
                           <a href="{% url 'myapp:gender_clothes' category_slug='bottoms' gender='male' %}" class="dropdown-list-link">Bottoms</a>
                        </li>
                        <li class="dropdown-list-item">
                           <a href="{% url 'myapp:gender_clothes' category_slug='sweaters' gender='male' %}" class="dropdown-list-link">Sweaters</a>
                        </li>
                        <li class="dropdown-list-item">
                           <a href="{% url 'myapp:gender_clothes' category_slug='jackets' gender='male' %}" class="dropdown-list-link">Jackets</a>
                        </li>
                     </ul>
                  </li>
                  <li class="second-nav-item">
                     <a href="#" class="second-nav-link">Women</a>
                     <ul class="dropdown-list">
                        <li class="dropdown-list-item">
                           <a href="{% url 'myapp:gender_clothes' category_slug='tops' gender='female' %}" class="dropdown-list-link">Tops</a>
                        </li>
                        <li class="dropdown-list-item">
                           <a href="{% url 'myapp:gender_clothes' category_slug='bottoms' gender='female' %}" class="dropdown-list-link">Bottoms</a>
                        </li>
                        <li class="dropdown-list-item">
                           <a href="{% url 'myapp:gender_clothes' category_slug='sweaters' gender='female' %}" class="dropdown-list-link">Sweaters</a>
                        </li>
                        <li class="dropdown-list-item">
                           <a href="{% url 'myapp:gender_clothes' category_slug='jackets' gender='female' %}" class="dropdown-list-link">Jackets</a>
                        </li>
                     </ul>
                  </li>
               </ul>
            </nav>

         </div>



        <div class="body">
            {% block body %}
            {% endblock %}
        </div>
    </body>
    <section class="contact">
      <div class="customer-support">
          <h1 class="customer-support-heading">Customer Support</h1>
          <a href="#" class="customer-support-element">Customer Service</a>
          <a href="#" class="customer-support-element">Shipping and Handling</a>
          <a href="#" class="customer-support-element">Returns</a>
          <a href="#" class="customer-support-element">About Us</a>
      </div>

      <div class="find-us">
          <h1 class="find-us-heading">Find Us</h1>
          <a href="#" class="customer-support-element">1-408-930-3376</a>
          <a href="#" class="customer-support-element">haque@sbcglobal.net</a>
      </div>

   </section>
</html>

myapp/templates/myapp/login.html
{% extends "myapp/layout.html" %}
{% load static %}


{% block body %}
   <span class="log-in">LOG IN</span>
   <div class="login-wrapper">
      {% if message %}
            <div class="login_message">{{ message }}</div>
      {% endif %}
      <form action="{% url 'myapp:login' %}" method="post" id="login-form" name="loginform">
         {% csrf_token %}
         <div class="field">
            <input class="input-details" type="email" name="email" id="email-login" placeholder=" " required>
            <label for="email" id="email-label">Email</label>
        </div>
        <div class="field">
           <input class="input-details" type="password" name="password" id="password-login" placeholder=" " required>
           <label class="password" id="password-label">Password</label>
        </div>
        <input id="login-btn" class="btn-top" type="submit" value="Login">
      </form>
    <span class="register-link">Don't have an account? <a href="{% url 'myapp:register' %}">Register here.</a></span>
   </div>
{% endblock %}


{% block script %}
    <script src="{% static 'myapp/login.js' %}"></script>
{% endblock %}

myapp/templates/myapp/register.html
{% extends "myapp/layout.html" %}
{% load static %}


{% block body %}
<span class="log-in">SIGN UP</span>
<div class="login-wrapper">
   <form action="{% url 'myapp:register' %}" method="post">
      {% csrf_token %}
      <div class="form-group">
         <label class="login-label">Email Address</label>
         <input  class="form-control" type="text" name="email" id="register_email" required>
     </div>
     <div class="form-group">
        <label class="login-label">Username</label>
        <input  class="form-control" type="text" name="username" id="register_username" required>
    </div>
     <div class="form-group">
        <label class="login-label">Password</label>
         <input class="form-control" type="password" name="password" id="register_password" required>
     </div>
     <div class="form-group">
        <label class="login-label">Confirm Password</label>
         <input class="form-control" type="password" name="confirm-password" id="confirm-password" required>
     </div>
     <input id="register-btn" class="btn-top" type="submit" value="Sign Up">
   </form>
<span class="register-link">Already have an account? <a href="{% url 'myapp:login' %}">Log in here.</a></span>
</div>

{% endblock %}

{% block script %}
    <script src="{% static 'myapp/register.js' %}"></script>
{% endblock %}

myapp/templates/myapp/search.html
{% extends "myapp/layout.html" %}

{% block body %}
<section class="clothing-products">
   {% if message %}
         <div class="search_message">{{ message }}</div>
   {% endif %}
   {% for clothing in clothes %}
      <div class="product">
         <img class="clothing-img" src="{{ clothing.image.url }}" width=100%>
         <a id="clothing-title" href="{% url 'myapp:clothing_description' clothing_id=clothing.pk slug=clothing.slug %}" class="product-details"> {{ clothing.name }}</a>
         <br>
         <span class="product-details">${{ clothing.price }}</span>
      </div>
   {% endfor %}
</section>

{% endblock %}